### ISSUE TITLE
Forward mucommander.com to the github.io page

### ISSUE THREAD

**Issue by sdruskat** [mucommander/mucommander.github.io#1]
I guess this is in the works anyway? That broken trac makes me crazy :).

Thanks for keeping up the maintenance! Great software!

**Comment by ahadas** [comment]
Hi,
Thanks :)

@m4xence do you think we can redirect mucommander.com to mucommander.github.io? sure, some more work still needs to be done, but I guess in its current state the github.io page is no worse than the official one

**Comment by ahadas** [comment]
Done
